### ISSUE TITLE
Icons overlapping text

### ISSUE THREAD

**Issue by hermannw** [mtatsuma/MMM-WeatherChart#38]
Hi @mtatsuma 

I updated my MagicMirror to V2.17.1 and installed your module yesterday.
It looks like I have the same problem as mentioned in issue #21 . iconWith and iconHeight don't seem to exist in the code any longer and I don't want to make the font smaller. 
Any suggestions on how to fix this?

Also: Is it possible to suppress the decimal values at the temperature? I don't think the predicted temperature will be THAT precise. :-)
Thanks for providing this great module!
Hermann

**Comment by mtatsuma** [comment]
Hi

Thank you for using this module.

When the `height` in your config is small (e.g. <= 300px), icons may overlap the data labels. It can be avoided if you can set `height` as larger value (e.g. >= 500px).

Another option is to set `datalabelsOffset` as a negative value, which makes the space between labels and lines smaller.

When I set `height: 300px`, `fontSize: 18` and `datalabelsOffset: -4`, it draws following chart.

![image](https://user-images.githubusercontent.com/48573325/137489435-d21f7286-c1ee-4d83-8d49-3579bcee3c1b.png)

The `iconWidth` and `iconHeight` options became unavailable when I updated Chart.js to v3.x due to a technical problem.
If you want to use these options, you can use an old version (e.g. v2.6.0) of MMM-WeatherChart. But I do not recommend to use the older versions because they are not tested well with the latest MagicMirror.

If you share your config options with me, I can check the config in my environment.

**Comment by hermannw** [comment]
Thank you tatsuma, that looks great! If yo could suppress the decimal points on the temperature, I would be a very happy camper! :-) I think it would look a lot cleaner and less crowded.

Hermann

**Comment by mtatsuma** [comment]
I'm sorry for my late response again.

I added a new config option `datalabelsRoundDecimalPlace`.
https://github.com/mtatsuma/MMM-WeatherChart/pull/41

Your problem will be solved by setting this option as `0` on your config after cloning the latest MMM-WeatherChart module.

like the follows

![image](https://user-images.githubusercontent.com/48573325/148001517-3607ccad-71a3-4be7-bdec-a4f97a3ba5fd.png)

**Comment by hermannw** [comment]
Wonderful! Thank you very much!
Happy New Year!
